apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-quickstart
  namespace: default
spec:
  image: docker.elastic.co/apm/apm-server-oss:7.10.2
  count: 1
  elasticsearchRef:
    name: quickstart
