apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-10-19T15:03:47Z"
  labels:
    app: magix
  name: magix
  namespace: default
  resourceVersion: "119447"
  selfLink: /api/v1/namespaces/default/services/magix
  uid: a3473951-fa8e-442f-9747-f7ec18395291
spec:
  clusterIP: 10.152.183.132
  clusterIPs:
  - 10.152.183.132
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32407
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: magix
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
