apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: tango-server
  name: tango-server
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tango-server
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tango-server
    spec:
      containers:
      - image: ingvord/axsis-tango-server:AxsisTangoServer-0.14
        imagePullPolicy: IfNotPresent
        name: axsis-virtual-tango-host
        env:
          - name: MAGIX_HOST
            value: localhost:32407
          - name: TANGO_HOST
            value: localhost:10000
        ports:
        - containerPort: 30100    
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File        
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
