apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-11-05T23:27:33Z"
  generation: 1
  labels:
    app: tango-server
  name: tango-server
  namespace: default
  resourceVersion: "7649"
  selfLink: /apis/apps/v1/namespaces/default/deployments/tango-server
  uid: f163485c-7091-413f-9cc8-34be462631bb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tango-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tango-server
    spec:
      containers:
      - image: ingvord/axsis-virtual-tango-host:AxsisTangoServer-0.3
        imagePullPolicy: IfNotPresent
        name: axsis-virtual-tango-host
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2021-11-05T23:27:33Z"
    lastUpdateTime: "2021-11-05T23:28:37Z"
    message: ReplicaSet "tango-server-5b8ffffc57" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-11-05T23:32:16Z"
    lastUpdateTime: "2021-11-05T23:32:16Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
