apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-10-19T14:33:56Z"
  labels:
    app: web
  name: web
  namespace: default
  resourceVersion: "116961"
  selfLink: /api/v1/namespaces/default/services/web
  uid: 37a69814-a82b-45ee-8db3-b277ee45cbcb
spec:
  clusterIP: 10.152.183.70
  clusterIPs:
  - 10.152.183.70
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32600
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
